name: Book store e2e Tests

on: 
  push:
    branches:
      - '**'

jobs:
  run:
    name: "cypress-run"
    runs-on: ubuntu-24.04
    container:
      image: cypress/included:13.16.0
      
    steps:
      # Copy code from repo
      - name: Checkout
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: npm install      

      # Run all Cypress tests
      - name: Run Cypress tests with Mocha reporter
        continue-on-error: true
        run: npx cypress run --reporter mochawesome --reporter-options reportDir=cypress/report,overwrite=false,html=false,json=true
      
      - name: List Files
        continue-on-error: true
        run: ls -lah cypress/report 

      #Verify reports generated successfully
      - name: Verify JSON reports
        run: |
          mkdir -p cypress/report
          ls -lah cypress/report
  

      # Merge the reports
      - name: Merge all the reports
        run: npx mochawesome-merge cypress/report/*.json > cypress/report/merged-report.json
  
      #Generate HTML report
      - name: Generate HTML report
        run: npx mochawesome-report-generator cypress/report/merged-report.json --reportDir cypress/report --reportFilename book-store-testing-report

      #Upload HTML report
      - name: Upload Cypress report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: cypress/report/*